[buildPlans.Iosevkb]
family = "Iosevkb"
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

  [buildPlans.Iosevkb.variants]
  inherits = "ss05"

    [buildPlans.Iosevkb.variants.design]
    capital-v = "straight-serifless"
    a = "double-storey-serifless"
    i = "tailed-serifed"
    j = "serifed"
    v = "straight-serifless"
    x = "straight-serifless"
    y = "straight-turn-serifless"
    z = "straight-serifless"
    lower-delta = "rounded"
    lower-lambda = "straight-turn"
    lower-mu = "tailed-serifless"
    lower-xi = "rounded"
    cyrl-capital-zhe = "symmetric-connected"
    cyrl-zhe = "symmetric-connected"
    cyrl-capital-ka = "curly-serifless"
    cyrl-ka = "curly-serifless"
    zero = "slashed-split"
    five = "oblique-flat-serifless"
    punctuation-dot = "round"
    asterisk = "penta-low"
    underscore = "low"
    paren = "normal"
    brace = "straight"
    ampersand = "et-toothless-corner"
    dollar = "through"
    bar = "natural-slope"
    partial-derivative = "straight-bar"
    micro-sign = "tailed-serifless"
    lig-ltgteq = "slanted"
    lig-equal-chain = "without-notch"
    lig-hyphen-chain = "without-notch"
    lig-single-arrow-bar = "without-notch"

    [buildPlans.Iosevkb.variants.italic]
    capital-f = "serifless"
    capital-i = "serifed"
    capital-k = "curly-top-left-and-bottom-right-serifed"
    a = "single-storey-serifless"
    e = "rounded"
    f = "tailed"
    g = "single-storey-earless-corner"
    l = "tailed-serifed"
    v = "curly-motion-serifed"

  [buildPlans.Iosevkb.ligations]
  inherits = "dlig"

[buildPlans.Iosevkb.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.Iosevkb.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.Iosevkb.widths.Extended]
shape = 720
menu = 7
css = "expanded"