# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
# Utilities
bind = $mainMod, Return, exec, kitty
bind = $mainMod SHIFT, Q, killactive, 
bind = $mainMod, M, exit, 
bind = $mainMod, E, exec, emacsclient -c -a ''
bind = $mainMod, V, togglefloating, 
bind = $mainMod, D, exec, rofi -show drun
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle
bind = $mainMod, S, focusmonitor, +1
bind = $mainMod, F, fullscreen,
bind = , Print, exec, grim -g "$(slurp)" - | wl-copy
bind = $mainMod SHIFT, S, movecurrentworkspacetomonitor, +1

# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d
bind = $mainMod, h, movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d
bind = $mainMod SHIFT, h, movewindow, l
bind = $mainMod SHIFT, l, movewindow, r
bind = $mainMod SHIFT, k, movewindow, u
bind = $mainMod SHIFT, j, movewindow, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, ampersand,  workspace, 1
bind = $mainMod, eacute,     workspace, 2
bind = $mainMod, quotedbl,   workspace, 3
bind = $mainMod, apostrophe, workspace, 4
bind = $mainMod, parenleft,  workspace, 5
bind = $mainMod, minus,      workspace, 6
bind = $mainMod, egrave,     workspace, 7
bind = $mainMod, underscore, workspace, 8
bind = $mainMod, ccedilla,   workspace, 9
bind = $mainMod, agrave,     workspace, 10

bind = $mainMod, 1,  workspace, 1
bind = $mainMod, 2,  workspace, 2
bind = $mainMod, 3,  workspace, 3
bind = $mainMod, 4,  workspace, 4
bind = $mainMod, 5,  workspace, 5
bind = $mainMod, 6,  workspace, 6
bind = $mainMod, 7,  workspace, 7
bind = $mainMod, 8,  workspace, 8
bind = $mainMod, 9,  workspace, 9
bind = $mainMod, 0,  workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, ampersand,  movetoworkspace, 1
bind = $mainMod SHIFT, eacute,     movetoworkspace, 2
bind = $mainMod SHIFT, quotedbl,   movetoworkspace, 3
bind = $mainMod SHIFT, apostrophe, movetoworkspace, 4
bind = $mainMod SHIFT, parenleft,  movetoworkspace, 5
bind = $mainMod SHIFT, minus,      movetoworkspace, 6
bind = $mainMod SHIFT, egrave,     movetoworkspace, 7
bind = $mainMod SHIFT, underscore, movetoworkspace, 8
bind = $mainMod SHIFT, ccedilla,   movetoworkspace, 9
bind = $mainMod SHIFT, agrave,     movetoworkspace, 10

bind = $mainMod SHIFT, 1,  movetoworkspace, 1
bind = $mainMod SHIFT, 2,  movetoworkspace, 2
bind = $mainMod SHIFT, 3,  movetoworkspace, 3
bind = $mainMod SHIFT, 4,  movetoworkspace, 4
bind = $mainMod SHIFT, 5,  movetoworkspace, 5
bind = $mainMod SHIFT, 6,  movetoworkspace, 6
bind = $mainMod SHIFT, 7,  movetoworkspace, 7
bind = $mainMod SHIFT, 8,  movetoworkspace, 8
bind = $mainMod SHIFT, 9,  movetoworkspace, 9
bind = $mainMod SHIFT, 0,  movetoworkspace, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Multimedia commands
bind = ,XF86AudioRaiseVolume, exec, ~/os-files/utilities/changeVolume.sh 2%+
bind = ,XF86AudioLowerVolume, exec, ~/os-files/utilities/changeVolume.sh 2%-
bind = ,XF86AudioMute       , exec, ~/os-files/utilities/changeVolume.sh mute

bind = ,XF86AudioMedia      , exec, kitty ncmpcpp
bind = ,XF86Tools           , exec, kitty ncmpcpp
bind = ,XF86AudioPause      , exec, ~/os-files/utilities/mpd_control.sh toggle
bind = ,XF86AudioPlay       , exec, ~/os-files/utilities/mpd_control.sh toggle
bind = ,XF86AudioPrev       , exec, ~/os-files/utilities/mpd_control.sh prev
bind = ,XF86AudioNext       , exec, ~/os-files/utilities/mpd_control.sh next