#: Color scheme {{{

#background #f9f5d7
background #f9f9ef
foreground #282828

background_opacity 0.8

background_blur 1

# background_image none
# background_image_layout tiled

# background_image_linear no
# dynamic_background_opacity no
# background_tint 0.0

# background_tint_gaps 1.0
# dim_opacity 0.4
# selection_foreground #000000
# selection_background #fffacd
#: The color table {{{

#: The 256 terminal colors. There are 8 basic colors, each color has a
#: dull and bright version, for the first 16 colors. You can set the
#: remaining 240 colors as color16 to color255.

color0 #000000
color8 #1c1c1c

#: black

color1  #cc241d
color9  #9d0006

#: red

color2  #98971q
color10 #79740e

#: green

color3  #d79921
color11 #b57614

#: yellow

color4  #458588
color12 #076678

#: blue

color5  #b16286
color13 #8f3f71

#: magenta

color6  #689d6a
color14 #427b58

#: cyan

color7  #bdae93
color15 #ffffff

#: white

# mark1_foreground black

#: Color for marks of type 1

# mark1_background #98d3cb

#: Color for marks of type 1 (light steel blue)

# mark2_foreground black

#: Color for marks of type 2

# mark2_background #f2dcd3

#: Color for marks of type 1 (beige)

# mark3_foreground black

#: Color for marks of type 3

# mark3_background #f274bc

#: Color for marks of type 3 (violet)

#: }}}

#: }}}