[bell]
animation = "EaseOutExpo"
args = ["--login"]
program = "/bin/bash"

[colors.bright]
black = "0x928374"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xdfbf8e"
yellow = "0xe3a84e"

[colors.normal]
black = "0x665c54"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xdfbf8e"
yellow = "0xe78a4e"

[colors.primary]
background = "0x282828"
foreground = "0xdfbf8e"

[cursor]
blink_interval = 200
blink_timeout = 0
thickness = 0.25
unfocused_hollow = false

[cursor.style]
blinking = "Always"
shape = "Underline"

[font]
size = 11.0

[font.normal]
family = "Cascadia Code"
style = "Regular"

[window]
opacity = 0.55

[window.dimensions]
columns = 214
lines = 56
